### ISSUE TITLE
Consigna Diagrama de clases: Creación del diagrama de clases

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#11]

**Comment by RoHu17** [comment]
https://drive.google.com/file/d/19YIWJZyqetYpqBvgZlJVJLJ2sZ0hCT2t/view?usp=sharing

**Comment by RoHu17** [comment]
Se confecciona el diagrama de clases para el Proyecto ArgBroker Demo.
Link: https://drive.google.com/file/d/11KhE7zqs5t0YK97YB2pndWW3IvNkHd9l/view?usp=sharing

**Comment by Mauri31** [comment]
Luego de la creacion del diagrama de clases y del modelo relacional, los comparamos y pudimos llegar a la forma final del diagrama de clases.
