### ISSUE TITLE
Consigna Ética: Describir la forma legal y otros procedimientos (Incisos 1 a 4)

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#13]

**Comment by Mauri31** [comment]
Teniendo en cuenta las clases, las leyes provistas por la profesora y  consultando otras leyes para conocer el funcionamiento de las empresas en Argentina, dejamos sentado los requerimientos para la formacion, registro y el funcionamiento de ARGBroker SRL. Ademas, especificamos nuestas funciones dentro de la empresa, los requisitos para la matriculacion y los requisitos que deben cumplir el codigo y la base de datos.
