### ISSUE TITLE
Consigna Ética: Casuísticas probables (Incisos 5 a 9)

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#15]

**Comment by Cesiaf** [comment]
Se responden los casos legales planteados en los incisos 5 a 9. En esta parte del trabajo han colaborado @Lighuennqn y @Cesiaf realizando la investigación y debatiendo hasta llegar a la respuesta planteada. El trabajo se verá reflejado en la entrada titulada "Ética y deontología" situada el el Wiki del repositorio.

**Comment by Lighuennqn** [comment]
Tras previa lectura de varias leyes como la Ley 7642, la Ley 25.326 de protección de los datos personales, la Ley 26.388 de delitos informáticos, la Ley 24.240 de Defensa del Consumidor, entre otras. Se realizó la redacción de las consignas establecidas relacionadas al proyecto ARGBroker.
