### ISSUE TITLE
Consigna Ética: Casuísticas probables (Incisos 10 a 15)

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#16]

**Comment by Barrenechea53Calderon** [comment]
Se observaron las leyes con respecto a la proteccion de datos personales ley 25.326 que puede respaldarse un broker, como tambien la ley 26388 de delitos informaticos. 
A nivel internacional el convenio de Budapest facilita la cooperación internacional y la asistencia mutua en la investigación y persecución de delitos informáticos, incluyendo la adulteración de datos.
Cuando los programadores incurren en una negligencia clientes afectados: Pueden recurrir a la Ley de Defensa del Consumidor (Ley 24.240) para reclamar daños y perjuicios.
Organismos profesionales (CPCIPC): ARGBroker debe informar al Colegio de Profesionales de la Ingeniería Civil y el Centro de Ingenieros de la Provincia de Córdoba quienes en base a la Ley 7642, evaluarán la conducta y sancionará en caso que haya sido negligente.
En cuanto a seguridad de los datosLey 25.326 de Protección de Datos Personales, ARGBroker debe designar un responsable de seguridad, implementar medidas técnicas (como cifrado y firewalls) y organizativas (políticas de acceso restringido), 
Con respecto a cambio de proveedor, transparencia por parte del programador, cooperar con el nuevo proveedor, transferencia segura de datos, 
En cuanto a divulgacion de datos CodeCrafters por divulgación de sus datos personales, la legislación a la que probablemente recurra es la Ley 25.326. Para respaldarse CodeCrafters debería: colaborar con toda la informacion a la autoridad.
Segun lo escrito anteriormente de las leyes son las más importantes para trabajar con etica, y dentro de la ley
