### ISSUE TITLE
Consigna Base de datos: Definir los atributos de las entidades

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#3]

**Comment by Barrenechea53Calderon** [comment]
Se definieron los atributos de las principales entidades:

Inversor

IdInversor
DNI
CUIT
Nombre
Apellido
Email
Domicilio
Acciones

IdAccion
Ticker
Nombre
Empresa
Sector
Operaciones

IdOperacion
IdCotizacion
IdTipoOperacion
IdInversor
Fecha
Hora
PrecioOperado
CantidadOperada
MontoTotal
ComisionBroker
Cotizaciones

IdCotizacion
IdAccion
Fecha
Hora
UltimoOperado
PrecioApertura
MinimoDiario
MaximoDiario
PrecioCierre
PrecioCompraActual
PrecioVentaActual
UltimoPrecioCierre
CantidadDisponible
Portafolio

IdPortafolio
IdInversor
SaldoCuentaPesos
TotalInvertidoActual
RendimientoTotal
