### ISSUE TITLE
Consigna Base de datos: Definir las relaciones entre las entidades

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#4]

**Comment by Lighuennqn** [comment]
Se realizo la determinación de las relaciones entre las entidades de la siguiente manera:
- Un Inversor tiene un Portafolio, a su ve puede tener muchas Operaciones y tiene un tipo de PerfilInversor en función de su objetivo y a su vez los inversores entre si pueden tener diferentes perfiles.
- Un Portafolio puede contener muchas Acciones y a su vez cada acción puede estar en muchos portafolios de inversores distintos (relación de muchos a muchos implementada con una tabla intermedia PortafolioAcciones).
- Operaciones registra transacciones asociadas a una Acción y a un Inversor, y cada operación depende de la cotización de una acción en el momento de operar, por ello se relaciona con la entidad Cotizaciones. Cada operación es de un TipoOperacion o compra o venta.
- TipoOperacion define si una operación es de compra o venta.
- Cotizaciones representa la evolución dinámica del precio de cada Acción, por ello se relaciona con Operaciones para indicar el precio de la acción al momento de la operación (una cotización puede estar en muchas operaciones, pero cada operación tiene una sola cotización), y se relaciona con Acciones ya que cada acción tiene distintas cotizaciones según el momento, pero cada cotización corresponde a una única acción.
Con esto se llego a un consenso grupal de lo establecido.
