### ISSUE TITLE
Consigna Base de datos: Normalización 

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#5]

**Comment by Lighuennqn** [comment]
Aplicamos el proceso de normalización para evitar que las entidades y sus atributos tengan redundancias o dependencias funcionales.

- 1FN: Cada tabla debe tener una clave primaria única y no se deben permitir valores repetidos en las columnas. Además, las tablas solo contienen valores atómicos.
- 2FN: Todos los atributos no clave son completamente dependientes de la clave primaria.
- 3FN: No hay dependencias transitivas entre atributos no clave.
