### ISSUE TITLE
Consigna Diagrama de clases: Identificación de las clases

### ISSUE THREAD

**Issue by CHRISTIANDAGATTI** [CodeCrafters8/SoftwareBroker#8]

**Comment by RoHu17** [comment]
Se Identidican las siguientes clases, para el Proyecto ArgBroker Demo.

Clases:

- Inversor.
- PerfilInversor.
- Operaciones.
- TipoOperacion
- Cotizaciones.
- Accion.
- Portafolio.
- PortafolioAcciones. 
- Sistema.
